# Generated by Django 5.2.12 on 2026-04-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productinfo',
            name='unique_product_info',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='seller',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Внешний ИД'),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='shop',
            name='permissions_order',
            field=models.BooleanField(default=True, verbose_name='Заказ разрешен'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего входа'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=0, verbose_name='Количество входов'),
        ),
        migrations.AddConstraint(
            model_name='productinfo',
            constraint=models.UniqueConstraint(fields=('product', 'external_id', 'shop'), name='unique_product_info'),
        ),
    ]
