# Generated by Django 5.2.12 on 2026-05-14 19:02

import backend.models
import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', imagekit.models.fields.ProcessedImageField(help_text='Оригинальное изображение (макс. 1920x1920px)', upload_to=backend.models.product_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), backend.models.validate_image_size], verbose_name='Оригинал')),
                ('preview', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Предварительный просмотр 400x400', null=True, upload_to=backend.models.product_image_path, verbose_name='Превью')),
                ('full_view', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Фото товара 1200x1200px', null=True, upload_to=backend.models.product_image_path, verbose_name='Полный просмотр')),
                ('is_main', models.BooleanField(default=False, help_text='Отметьте, если это главное фото товара', verbose_name='Основное фото')),
                ('alt_text', models.CharField(blank=True, help_text='Текст для SEO и accessibility', max_length=255, verbose_name='Alt-текст')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше позиция', verbose_name='Порядок сортировки')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.productinfo', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ('sort_order', 'uploaded_at'),
            },
        ),
    ]
