# Generated by Django 5.2.12 on 2026-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('owner', 'Владелец'), ('buyer', 'Покупатель'), ('admin', 'Администратор')], default='buyer', max_length=5, verbose_name='Тип пользователя'),
        ),
    ]
