# Generated by Django 5.2.12 on 2026-04-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='sell_up_to',
            field=models.CharField(default='', max_length=10, verbose_name='Продать до'),
        ),
    ]
