# Generated by Django 5.2.12 on 2026-04-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user', 'city', 'street', 'house'), name='unique_user_address'),
        ),
    ]
