# orders/settings.py
"""
Django settings for orders project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

from dotenv import load_dotenv
from pathlib import Path
import dj_database_url

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from django.http import Http404
from django.core.exceptions import PermissionDenied
from rest_framework.exceptions import Throttled


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'rest_framework',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
    'cacheops',
    'imagekit',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'social_django',
    'backend',
    'baton.autodiscover',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'orders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orders.wsgi.application'

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,                # опциональный пул соединений
        ssl_require=False,               # True для продакшена
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'backend.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_HOST_USER = os.getenv('MY_EMAIL')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
EMAIL_PORT = 465
EMAIL_USE_SSL = True
SERVER_EMAIL = os.getenv('MY_EMAIL')
DEFAULT_FROM_EMAIL = os.getenv('MY_EMAIL')

if DEBUG:
    BACKEND_URL = 'http://localhost:8000'  # Разработка
    FRONTEND_URL = 'http://localhost:3000'
else:
    BACKEND_URL = 'https://api.your-domain.com'  # ваш бэкенд
    FRONTEND_URL = 'https://your-domain.com'  # ваш фронтенд

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',  # Для анонимных пользователей
        'user': '1000/day',  # Для аутентифицированных пользователей
        'register': '3/hour',  # Для регистрации
        'login': '5/minute',  # Для входа
        'confirm_email': '10/minute',  # Для подтверждения email
        'partner_update': '2/hour',  # Для обновления прайса
    }
}

SPECTACULAR_SETTINGS = {
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'TITLE': 'Orders API',
    'DESCRIPTION': 'API для управления заказами',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'FileType': 'image/jpeg image/png image/webp',
    },
}

COMPONENT_SPLIT_REQUEST = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для импорта YAML файлов
YAML_IMPORT_ALLOWED_PATHS = [
    '/data/imports/',
    '/var/www/uploads/',
    './imports/',
    './uploads/',
    '/tmp/yaml_imports/',  # Добавляем временную папку
]

# Максимальный размер файла для импорта (в байтах)
YAML_MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB

# Таймаут для загрузки по URL (в секундах)
YAML_DOWNLOAD_TIMEOUT = 30

# Разрешенные MIME типы для YAML файлов
YAML_ALLOWED_MIME_TYPES = [
    'application/x-yaml',
    'text/yaml',
    'text/x-yaml',
    'application/yaml',
    'text/plain',  # Некоторые серверы возвращают text/plain для YAML
]

# Настройки для парсинга YAML
YAML_LOADER = 'yaml.SafeLoader'  # Безопасный загрузчик

# django-imagekit — асинхронная генерация миниатюр
IMAGEKIT_DEFAULT_CACHEFILE_BACKEND = 'imagekit.cachefiles.backends.Async'
IMAGEKIT_DEFAULT_CACHEFILE_STRATEGY = 'imagekit.cachefiles.strategies.Optimistic'

# Настройки кеша (опционально, для хранения сгенерированных миниатюр)
IMAGEKIT_CACHEFILE_DIR = 'cache/images'

# ========== SOCIAL-AUTH (Яндекс OAuth2) ==========
AUTHENTICATION_BACKENDS = (
    'social_core.backends.yandex.YandexOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

AUTHENTICATION_BACKENDS = (
    'social_core.backends.yandex.YandexOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Яндекс OAuth2
SOCIAL_AUTH_YANDEX_OAUTH2_KEY = os.getenv('YANDEX_APP_ID', '')
SOCIAL_AUTH_YANDEX_OAUTH2_SECRET = os.getenv('YANDEX_APP_SECRET', '')
SOCIAL_AUTH_YANDEX_OAUTH2_SCOPE = ['login:email', 'login:info', 'login:avatar']

# Используем email как username
USERNAME_FIELD = 'email'

# Поля, которые заполняются из соцсети
SOCIAL_AUTH_USER_FIELDS = ['email', 'first_name', 'last_name']

# Разрешаем обновление всех полей
SOCIAL_AUTH_PROTECTED_USER_FIELDS = []

# Указываем URL для редиректа
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/api/social-auth/complete/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/api/social-auth/error/'

# Pipeline — цепочка обработки после авторизации
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'backend.pipeline.associate_by_email_or_create',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'backend.pipeline.save_yandex_data',
)

# URL-префикс для social-auth
SOCIAL_AUTH_URL_NAMESPACE = 'social'
LOGIN_URL = '/api/social-auth/login/yandex-oauth2/'

# Sentry — мониторинг ошибок
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
SENTRY_ENVIRONMENT = 'development' if DEBUG else 'production'

def _strip_sensitive_data(event, hint):
    """Удаляем пароли, токены и ключи из данных перед отправкой в Sentry"""
    if 'request' in event:
        if 'data' in event['request']:
            data = event['request']['data']
            if isinstance(data, dict):
                sensitive_fields = ['password', 'token', 'secret', 'api_key',
                                    'access', 'refresh', 'csrfmiddlewaretoken']
                for field in sensitive_fields:
                    if field in data:
                        data[field] = '***'

        # Также чистим query string
        if 'query_string' in event['request']:
            # можно дополнительно обработать query parameters
            pass

    return event

def _before_sentry_send(event, hint):
    """
    Фильтр событий перед отправкой в Sentry.
    Позволяет отбрасывать неважные ошибки.
    """
    if 'exc_info' in hint:
        exc_type, exc_value, tb = hint['exc_info']

        if exc_type == Http404:
            return None
        if exc_type == PermissionDenied:
            return None
        if exc_type == Throttled:
            return None
    return event

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style='url',
                middleware_spans=True,
            ),
            # RedisIntegration(),
            LoggingIntegration(
                level=None,
                event_level=None,
            ),
        ],
        environment=SENTRY_ENVIRONMENT,
        release='orders-api@1.0.0',

        traces_sample_rate=1.0 if DEBUG else 0.2,
        profiles_sample_rate=1.0 if DEBUG else 0.1,

        send_default_pii=False,
        max_breadcrumbs=50,

        # Цепочка фильтров
        before_send=lambda event, hint: _strip_sensitive_data(
            _before_sentry_send(event, hint),
            hint
        ),
    )

# ========== CELERY CONFIGURATION ==========

# Брокер сообщений — Redis (локально или через переменную окружения)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')

# Бэкенд для хранения результатов выполнения задач
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND',
                                  'redis://localhost:6379/0')

# Формат сериализации
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Часовой пояс для Celery
CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_ENABLE_UTC = True

# Настройка количества одновременных задач (воркеров)
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100

# Поведение при падении задачи: повторять 3 раза с экспоненциальной задержкой
CELERY_TASK_DEFAULT_RETRY_DELAY = 60        # 60 секунд до первого повтора
CELERY_TASK_MAX_RETRIES = 3                 # максимум 3 повтора
CELERY_TASK_ACKS_LATE = True                # подтверждение после выполнения
CELERY_TASK_REJECT_ON_WORKER_LOST = True    # перезапуск при падении воркера

# Настройка очередей (можно разделить задачи по важности)
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_QUEUES = {
    'default': {
        'exchange': 'default',
        'routing_key': 'default',
    },
    'email': {                     # отдельная очередь для email
        'exchange': 'email',
        'routing_key': 'email',
    },
}

# ========== CELERY BEAT SCHEDULE ==========

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-tokens': {
        'task': 'backend.tasks.cleanup_expired_tokens_task',
        'schedule': crontab(hour=3, minute=0),  # Каждый день в 3:00
        'options': {'queue': 'default'},
    },
    'cleanup-expired-baskets': {
        'task': 'backend.tasks.cleanup_expired_baskets_task',
        'schedule': crontab(hour=4, minute=0),  # Каждый день в 4:00
        'options': {'queue': 'default'},
    },
}

# Redis — бэкенд для кэша

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'PARSER_CLASS': 'redis.connection.HiredisParser',
        },
        'KEY_PREFIX': 'myproject',
        'TIMEOUT': 60 * 15,  # 15 минут по умолчанию
    }
}

# Cacheops — автоматическое кэширование запросов

CACHEOPS_REDIS = os.getenv('REDIS_URL', 'redis://localhost:6379/1')

CACHEOPS = {
    # Магазины — кэшируем всё на 30 минут
    'backend.shop': {
        'ops': 'all',
        'timeout': 60 * 30,
    },
    # Категории — кэшируем всё на 30 минут
    'backend.category': {
        'ops': 'all',
        'timeout': 60 * 30,
    },
    # Информация о товарах — кэшируем всё на 10 минут
    'backend.productinfo': {
        'ops': 'all',
        'timeout': 60 * 10,
    },
    # Модель Product (основная) — кэшируем всё на 10 минут
    'backend.product': {
        'ops': 'all',
        'timeout': 60 * 10,
    },
    # Параметры товаров — кэшируем на 10 минут
    'backend.productparameter': {
        'ops': 'all',
        'timeout': 60 * 10,
    },
    # Остальные модели backend — кэшируем только get и fetch на 5 минут
    'backend.': {
        'ops': ('get', 'fetch'),
        'timeout': 60 * 5,
    },
    # Админку, auth, сессии и соцсети не кэшируем
    'auth.*': None,
    'admin.*': None,
    'sessions.*': None,
    'contenttypes.*': None,
    'social_django.*': None,
}

# Время жизни кэша по умолчанию (если не указано в CACHEOPS)
CACHEOPS_DEGRADE_ON_FAILURE = True   # если Redis упал — продолжаем без кэша
CACHEOPS_ENABLED = True              # включить кэширование

# ========== DJANGO-BATON CONFIGURATION ==========

BATON = {
    # 🌐 Внешний вид и брендинг
    'SITE_HEADER': 'Orders Admin Panel',
    'SITE_TITLE': 'Orders Admin',
    'INDEX_TITLE': 'Панель управления заказами',
    'SUPPORT_HREF': 'https://t.me/your_support',
    'COPYRIGHT': '© 2026 Orders API Team',

    # 🎨 Тема оформления
    'THEME': 'default',
    'THEME_TOGGLE': 'default',

    # 📌 Collapsible сайдбар (боковое меню)
    'MENU_ALWAYS_COLLAPSED': False,
    'MENU_TITLE': 'Меню',
    'MENU_ICONS': {
        'User': 'fas fa-user',
        'Shop': 'fas fa-store',
        'Category': 'fas fa-tags',
        'Product': 'fas fa-box',
        'ProductInfo': 'fas fa-info-circle',
        'Parameter': 'fas fa-sliders-h',
        'ProductParameter': 'fas fa-cog',
        'Contact': 'fas fa-address-card',
        'Phone': 'fas fa-phone',
        'Order': 'fas fa-shopping-cart',
        'OrderItem': 'fas fa-receipt',
        'ConfirmEmailToken': 'fas fa-envelope',
        'ProductImage': 'fas fa-image',
        'Group': 'fas fa-users-cog',
        'LogEntry': 'fas fa-history',
    },

    # 📂 Группировка приложений в сайдбаре
    'MENU_ORDER': [
        {
            'label': 'Пользователи',
            'icon': 'fas fa-user-friends',
            'models': [
                'backend.User',
                'backend.Contact',
                'backend.Phone',
                'backend.ConfirmEmailToken',
                'auth.Group',
            ]
        },
        {
            'label': 'Товары и каталог',
            'icon': 'fas fa-boxes',
            'models': [
                'backend.Shop',
                'backend.Category',
                'backend.Product',
                'backend.ProductInfo',
                'backend.Parameter',
                'backend.ProductParameter',
                'backend.ProductImage',
            ]
        },
        {
            'label': 'Заказы',
            'icon': 'fas fa-truck',
            'models': [
                'backend.Order',
                'backend.OrderItem',
            ]
        },
        {
            'label': 'Логи и аудит',
            'icon': 'fas fa-clipboard-list',
            'models': [
                'admin.LogEntry',
            ]
        },
    ],

    # 🧩 Фильтры как select2 (удобный поиск)
    'SELECT2': True,
    'SELECT2_CSS': True,
    'SELECT2_JS': True,

    # 🎯 Collapsible inline-блоки
    'COLLAPSABLE_INLINE_ADMIN': True,
    'INLINE_COLLAPSED': False,

    # 📊 Показывать тоггл для фильтров
    'SHOW_FILTERS_TOGGLE': True,

    # 🔍 Дополнительные настройки
    'SEARCH_FIELD': {
        'placeholder': 'Поиск по всей админке...',
        'submit_btn': 'Найти',
    },

    # 🗑️ Подтверждение массовых действий
    'CONFIRM_CHANGES': True,
    'CONFIRM_DELETE': True,

    # 🖼️ Аватарка пользователя (если есть поле avatar)
    'GRAVATAR_DEFAULT_IMAGE': 'mp',
    'GRAVATAR_ENABLED': False,
    'AVATAR_FIELD': 'avatar',
    'AVATAR_URL_FIELD': 'avatar_url',

    # 📱 Адаптивность
    'MOBILE_FILTERS': True,
    'MOBILE_HORIZONTAL': True,

    # 🔧 Экспериментальные функции
    'CHANGELIST_FILTERS_IN_MODAL': True,
    'CHANGEFORM_FIXED_SUBMIT_ROW': True,
}
